/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as EvalsRouteImport } from './routes/evals'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContentRouteImport } from './routes/content'
import { Route as MediaRouteImport } from './routes/media'
import { Route as CampaignsNewRouteImport } from './routes/campaigns.new'
import { Route as ApiAgentChatRouteImport } from './routes/api/agent-chat'
import { Route as ApiSetupRouteImport } from './routes/api/setup'
import { Route as CampaignsIdHistoryRouteImport } from './routes/campaigns.$id.history'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalsRoute = EvalsRouteImport.update({
  id: '/evals',
  path: '/evals',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsNewRoute = CampaignsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CampaignsRoute,
} as any)
const ApiAgentChatRoute = ApiAgentChatRouteImport.update({
  id: '/api/agent-chat',
  path: '/api/agent-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetupRoute = ApiSetupRouteImport.update({
  id: '/api/setup',
  path: '/api/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdHistoryRoute = CampaignsIdHistoryRouteImport.update({
  id: '/$id/history',
  path: '/$id/history',
  getParentRoute: () => CampaignsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/content': typeof ContentRoute
  '/evals': typeof EvalsRoute
  '/media': typeof MediaRoute
  '/skills': typeof SkillsRoute
  '/workspace': typeof WorkspaceRoute
  '/api/agent-chat': typeof ApiAgentChatRoute
  '/api/setup': typeof ApiSetupRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/campaigns/$id/history': typeof CampaignsIdHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/content': typeof ContentRoute
  '/evals': typeof EvalsRoute
  '/media': typeof MediaRoute
  '/skills': typeof SkillsRoute
  '/workspace': typeof WorkspaceRoute
  '/api/agent-chat': typeof ApiAgentChatRoute
  '/api/setup': typeof ApiSetupRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/campaigns/$id/history': typeof CampaignsIdHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/content': typeof ContentRoute
  '/evals': typeof EvalsRoute
  '/media': typeof MediaRoute
  '/skills': typeof SkillsRoute
  '/workspace': typeof WorkspaceRoute
  '/api/agent-chat': typeof ApiAgentChatRoute
  '/api/setup': typeof ApiSetupRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/campaigns/$id/history': typeof CampaignsIdHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaigns'
    | '/content'
    | '/evals'
    | '/media'
    | '/skills'
    | '/workspace'
    | '/api/agent-chat'
    | '/api/setup'
    | '/campaigns/new'
    | '/campaigns/$id/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campaigns'
    | '/content'
    | '/evals'
    | '/media'
    | '/skills'
    | '/workspace'
    | '/api/agent-chat'
    | '/api/setup'
    | '/campaigns/new'
    | '/campaigns/$id/history'
  id:
    | '__root__'
    | '/'
    | '/campaigns'
    | '/content'
    | '/evals'
    | '/media'
    | '/skills'
    | '/workspace'
    | '/api/agent-chat'
    | '/api/setup'
    | '/campaigns/new'
    | '/campaigns/$id/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignsRoute: typeof CampaignsRouteWithChildren
  ContentRoute: typeof ContentRoute
  EvalsRoute: typeof EvalsRoute
  MediaRoute: typeof MediaRoute
  SkillsRoute: typeof SkillsRoute
  WorkspaceRoute: typeof WorkspaceRoute
  ApiAgentChatRoute: typeof ApiAgentChatRoute
  ApiSetupRoute: typeof ApiSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evals': {
      id: '/evals'
      path: '/evals'
      fullPath: '/evals'
      preLoaderRoute: typeof EvalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/new': {
      id: '/campaigns/new'
      path: '/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof CampaignsNewRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/api/agent-chat': {
      id: '/api/agent-chat'
      path: '/api/agent-chat'
      fullPath: '/api/agent-chat'
      preLoaderRoute: typeof ApiAgentChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/setup': {
      id: '/api/setup'
      path: '/api/setup'
      fullPath: '/api/setup'
      preLoaderRoute: typeof ApiSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id/history': {
      id: '/campaigns/$id/history'
      path: '/$id/history'
      fullPath: '/campaigns/$id/history'
      preLoaderRoute: typeof CampaignsIdHistoryRouteImport
      parentRoute: typeof CampaignsRoute
    }
  }
}

interface CampaignsRouteChildren {
  CampaignsNewRoute: typeof CampaignsNewRoute
  CampaignsIdHistoryRoute: typeof CampaignsIdHistoryRoute
}

const CampaignsRouteChildren: CampaignsRouteChildren = {
  CampaignsNewRoute: CampaignsNewRoute,
  CampaignsIdHistoryRoute: CampaignsIdHistoryRoute,
}

const CampaignsRouteWithChildren = CampaignsRoute._addFileChildren(
  CampaignsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignsRoute: CampaignsRouteWithChildren,
  ContentRoute: ContentRoute,
  EvalsRoute: EvalsRoute,
  MediaRoute: MediaRoute,
  SkillsRoute: SkillsRoute,
  WorkspaceRoute: WorkspaceRoute,
  ApiAgentChatRoute: ApiAgentChatRoute,
  ApiSetupRoute: ApiSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
